### PR TITLE
Add Google Blobstore support

### PR DESCRIPTION
**Pull request by stephenc**
Adds support for Google Blobstore Storage

(tests are disabled by default as testing requires a valid google project configuration)

### CODE REVIEW

**Comment by stephenc** [comment]
Test failure seems to be lack of S3 credentials:

```
=== RUN   TestBlobstoreS3

    blobstore_test.go:102: 

        	Error Trace:	blobstore_test.go:102

        	Error:      	Expected nil, but got: &errors.errorString{s:"could not create blobstore \"test-blobstore-s3\": HTTP: 500, ERROR: (ID 05863488-3c33-4d5b-848c-aa12c1f92c97) org.sonatype.nexus.blobstore.api.BlobStoreException: Unable to initialize blob store bucket: terraform-provider-nexus-s3-test, Cause: Unable to execute HTTP request: terraform-provider-nexus-s3-test.s3.us-central-1.amazonaws.com"}

        	Test:       	TestBlobstoreS3

    blobstore_test.go:106: 

        	Error Trace:	blobstore_test.go:106

        	Error:      	Expected value not to be nil.

        	Test:       	TestBlobstoreS3

--- FAIL: TestBlobstoreS3 (5.36s)
```

**Comment by anmoel** [comment]
Hi @stephenc,

with which version did you test this pull request? I cannot find any API for the Google blobstore in the newest published version of nexus3. 

kind regards
André

**Comment by stephenc** [comment]
There's a oss plugin that provides it. The start-docker.sh in this PR will set up the plugin

**Comment by stephenc** [comment]
I don’t have the energy to pull this over the line. Feel free to take these changes in your own PR if they are wanted

**Pull request closed without merging**
