### PR TITLE
feat: Add option to run script with payload

### PR DESCRIPTION
**Pull request by nduyphuong**
This is useful in case we want to run script with parameter, eg script to create [clean up policy](https://github.com/idealista/nexus-role/blob/master/files/scripts/cleanup_policy.groovy)

### CODE REVIEW

**Comment by nduyphuong** [comment]
@anmoel Can we get this one reviewed, thanks a lot

**Review by anmoel — APPROVED** [review]
lgtm

**Comment by nduyphuong** [comment]
@anmoel  i've implemented update to support create cleanup policy resources also, will be more than happy to contribute back the change to upstream

**Comment by anmoel** [comment]
@nduyphuong, 

thanks for your PR.
This PR will included in the next release, which i will create tomorrow.

**Pull request merged**
